# Change these first
owner: voletro # Your GitHub organization or username, where this repository lives
repo: schoology-status # The name of this repository

sites:
  - name: Schoology App
    url: https://app.schoology.com
  - name: Main Schoology Page
    url: https://schoology.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /schoology-status
  logoUrl: https://lh6.googleusercontent.com/-Mxb88hjGKg4/AAAAAAAAAAI/AAAAAAAAAAA/BgtKhnkT5Sk/s0-c-k-no-ns/photo.jpg
  name: Schoology Status
  introTitle: "**Schoology** Status Page (Unofficial)"
  introMessage: This is a status page for Schoology, as it always seems to be down.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
